/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.7
 */

#ifndef _PyKDLAPI_H
#define _PyKDLAPI_H

#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_ChainIkSolverVel_pinv_givens 0
#define sipName_ChainIkSolverVel_pinv_givens &sipStrings_PyKDL[0]
#define sipNameNr_updateInternalDataStructures 29
#define sipName_updateInternalDataStructures &sipStrings_PyKDL[29]
#define sipNameNr_ChainFkSolverVel_recursive 58
#define sipName_ChainFkSolverVel_recursive &sipStrings_PyKDL[58]
#define sipNameNr_ChainFkSolverPos_recursive 85
#define sipName_ChainFkSolverPos_recursive &sipStrings_PyKDL[85]
#define sipNameNr_ChainIkSolverVel_pinv_nso 112
#define sipName_ChainIkSolverVel_pinv_nso &sipStrings_PyKDL[112]
#define sipNameNr_ChainJntToJacDotSolver 138
#define sipName_ChainJntToJacDotSolver &sipStrings_PyKDL[138]
#define sipNameNr_ChainIkSolverPos_NR_JL 161
#define sipName_ChainIkSolverPos_NR_JL &sipStrings_PyKDL[161]
#define sipNameNr_JntSpaceInertiaMatrix 184
#define sipName_JntSpaceInertiaMatrix &sipStrings_PyKDL[184]
#define sipNameNr_ChainIkSolverVel_wdls 206
#define sipName_ChainIkSolverVel_wdls &sipStrings_PyKDL[206]
#define sipNameNr_ChainIkSolverVel_pinv 228
#define sipName_ChainIkSolverVel_pinv &sipStrings_PyKDL[228]
#define sipNameNr_ChainIkSolverPos_LMA 250
#define sipName_ChainIkSolverPos_LMA &sipStrings_PyKDL[250]
#define sipNameNr_getRotationalInertia 271
#define sipName_getRotationalInertia &sipStrings_PyKDL[271]
#define sipNameNr_292 292
#define sipName_292 &sipStrings_PyKDL[292]
#define sipNameNr_ChainJntToJacSolver 312
#define sipName_ChainJntToJacSolver &sipStrings_PyKDL[312]
#define sipNameNr_ChainIkSolverPos_NR 332
#define sipName_ChainIkSolverPos_NR &sipStrings_PyKDL[332]
#define sipNameNr_ChainIdSolver_RNE 352
#define sipName_ChainIdSolver_RNE &sipStrings_PyKDL[352]
#define sipNameNr_RotationalInertia 274
#define sipName_RotationalInertia &sipStrings_PyKDL[274]
#define sipNameNr_ChainIkSolverVel 370
#define sipName_ChainIkSolverVel &sipStrings_PyKDL[370]
#define sipNameNr_ChainIkSolverPos 387
#define sipName_ChainIkSolverPos &sipStrings_PyKDL[387]
#define sipNameNr_ChainFkSolverVel 404
#define sipName_ChainFkSolverVel &sipStrings_PyKDL[404]
#define sipNameNr_ChainFkSolverPos 421
#define sipName_ChainFkSolverPos &sipStrings_PyKDL[421]
#define sipNameNr_MultiplyJacobian 438
#define sipName_MultiplyJacobian &sipStrings_PyKDL[438]
#define sipNameNr_RigidBodyInertia 455
#define sipName_RigidBodyInertia &sipStrings_PyKDL[455]
#define sipNameNr_Joint__JointType 472
#define sipName_Joint__JointType &sipStrings_PyKDL[472]
#define sipNameNr_getNrOfSegments 489
#define sipName_getNrOfSegments &sipStrings_PyKDL[489]
#define sipNameNr_changeRefFrame 505
#define sipName_changeRefFrame &sipStrings_PyKDL[505]
#define sipNameNr_changeRefPoint 520
#define sipName_changeRefPoint &sipStrings_PyKDL[520]
#define sipNameNr_newNrOfColumns 535
#define sipName_newNrOfColumns &sipStrings_PyKDL[535]
#define sipNameNr_JntToCoriolis 550
#define sipName_JntToCoriolis &sipStrings_PyKDL[550]
#define sipNameNr_ChainDynParam 564
#define sipName_ChainDynParam &sipStrings_PyKDL[564]
#define sipNameNr_ChainIdSolver 578
#define sipName_ChainIdSolver &sipStrings_PyKDL[578]
#define sipNameNr_getNrOfJoints 592
#define sipName_getNrOfJoints &sipStrings_PyKDL[592]
#define sipNameNr_getFrameToTip 606
#define sipName_getFrameToTip &sipStrings_PyKDL[606]
#define sipNameNr_GetQuaternion 620
#define sipName_GetQuaternion &sipStrings_PyKDL[620]
#define sipNameNr_JntToGravity 634
#define sipName_JntToGravity &sipStrings_PyKDL[634]
#define sipNameNr_DH_Craig1989 647
#define sipName_DH_Craig1989 &sipStrings_PyKDL[647]
#define sipNameNr_GetTwistDot 660
#define sipName_GetTwistDot &sipStrings_PyKDL[660]
#define sipNameNr_RotationVel 672
#define sipName_RotationVel &sipStrings_PyKDL[672]
#define sipNameNr_JntToJacDot 684
#define sipName_JntToJacDot &sipStrings_PyKDL[684]
#define sipNameNr__eps_joints 696
#define sipName__eps_joints &sipStrings_PyKDL[696]
#define sipNameNr_setWeightJS 708
#define sipName_setWeightJS &sipStrings_PyKDL[708]
#define sipNameNr_setWeightTS 720
#define sipName_setWeightTS &sipStrings_PyKDL[720]
#define sipNameNr_JntArrayVel 732
#define sipName_JntArrayVel &sipStrings_PyKDL[732]
#define sipNameNr_getTypeName 744
#define sipName_getTypeName &sipStrings_PyKDL[744]
#define sipNameNr_JointOrigin 756
#define sipName_JointOrigin &sipStrings_PyKDL[756]
#define sipNameNr_GetEulerZYX 768
#define sipName_GetEulerZYX &sipStrings_PyKDL[768]
#define sipNameNr_GetEulerZYZ 780
#define sipName_GetEulerZYZ &sipStrings_PyKDL[780]
#define sipNameNr_GetRotAngle 792
#define sipName_GetRotAngle &sipStrings_PyKDL[792]
#define sipNameNr_ReverseSign 804
#define sipName_ReverseSign &sipStrings_PyKDL[804]
#define sipNameNr___setitem__ 816
#define sipName___setitem__ &sipStrings_PyKDL[816]
#define sipNameNr___getitem__ 828
#define sipName___getitem__ &sipStrings_PyKDL[828]
#define sipNameNr_std__string 840
#define sipName_std__string &sipStrings_PyKDL[840]
#define sipNameNr_getWeights 852
#define sipName_getWeights &sipStrings_PyKDL[852]
#define sipNameNr_setWeights 863
#define sipName_setWeights &sipStrings_PyKDL[863]
#define sipNameNr_changeBase 874
#define sipName_changeBase &sipStrings_PyKDL[874]
#define sipNameNr_chain_root 885
#define sipName_chain_root &sipStrings_PyKDL[885]
#define sipNameNr_getSegment 896
#define sipName_getSegment &sipStrings_PyKDL[896]
#define sipNameNr_addSegment 907
#define sipName_addSegment &sipStrings_PyKDL[907]
#define sipNameNr_setInertia 918
#define sipName_setInertia &sipStrings_PyKDL[918]
#define sipNameNr_getInertia 929
#define sipName_getInertia &sipStrings_PyKDL[929]
#define sipNameNr_Quaternion 623
#define sipName_Quaternion &sipStrings_PyKDL[623]
#define sipNameNr_SetInverse 940
#define sipName_SetInverse &sipStrings_PyKDL[940]
#define sipNameNr_JntToMass 951
#define sipName_JntToMass &sipStrings_PyKDL[951]
#define sipNameNr_VectorVel 961
#define sipName_VectorVel &sipStrings_PyKDL[961]
#define sipNameNr_doubleVel 971
#define sipName_doubleVel &sipStrings_PyKDL[971]
#define sipNameNr_getOptPos 981
#define sipName_getOptPos &sipStrings_PyKDL[981]
#define sipNameNr_setOptPos 991
#define sipName_setOptPos &sipStrings_PyKDL[991]
#define sipNameNr_setLambda 1001
#define sipName_setLambda &sipStrings_PyKDL[1001]
#define sipNameNr_CartToJnt 1011
#define sipName_CartToJnt &sipStrings_PyKDL[1011]
#define sipNameNr_JntToCart 1021
#define sipName_JntToCart &sipStrings_PyKDL[1021]
#define sipNameNr_segmentNr 1031
#define sipName_segmentNr &sipStrings_PyKDL[1031]
#define sipNameNr_setColumn 1041
#define sipName_setColumn &sipStrings_PyKDL[1041]
#define sipNameNr_getColumn 1051
#define sipName_getColumn &sipStrings_PyKDL[1051]
#define sipNameNr_chain_tip 1061
#define sipName_chain_tip &sipStrings_PyKDL[1061]
#define sipNameNr_hook_name 1071
#define sipName_hook_name &sipStrings_PyKDL[1071]
#define sipNameNr_root_name 1081
#define sipName_root_name &sipStrings_PyKDL[1081]
#define sipNameNr_JointAxis 1091
#define sipName_JointAxis &sipStrings_PyKDL[1091]
#define sipNameNr_stiffness 1101
#define sipName_stiffness &sipStrings_PyKDL[1101]
#define sipNameNr_TransAxis 1111
#define sipName_TransAxis &sipStrings_PyKDL[1111]
#define sipNameNr_JointType 479
#define sipName_JointType &sipStrings_PyKDL[479]
#define sipNameNr_v_base_AB 1121
#define sipName_v_base_AB &sipStrings_PyKDL[1121]
#define sipNameNr_Integrate 1131
#define sipName_Integrate &sipStrings_PyKDL[1131]
#define sipNameNr_frequency 1141
#define sipName_frequency &sipStrings_PyKDL[1141]
#define sipNameNr_SetToZero 1151
#define sipName_SetToZero &sipStrings_PyKDL[1151]
#define sipNameNr_Normalize 1161
#define sipName_Normalize &sipStrings_PyKDL[1161]
#define sipNameNr_coriolis 1171
#define sipName_coriolis &sipStrings_PyKDL[1171]
#define sipNameNr_TwistVel 1180
#define sipName_TwistVel &sipStrings_PyKDL[1180]
#define sipNameNr_GetTwist 1189
#define sipName_GetTwist &sipStrings_PyKDL[1189]
#define sipNameNr_GetFrame 1198
#define sipName_GetFrame &sipStrings_PyKDL[1198]
#define sipNameNr_FrameVel 1207
#define sipName_FrameVel &sipStrings_PyKDL[1207]
#define sipNameNr_q_dotdot 1216
#define sipName_q_dotdot &sipStrings_PyKDL[1216]
#define sipNameNr_JntToJac 1225
#define sipName_JntToJac &sipStrings_PyKDL[1225]
#define sipNameNr_getAlpha 1234
#define sipName_getAlpha &sipStrings_PyKDL[1234]
#define sipNameNr_setAlpha 1243
#define sipName_setAlpha &sipStrings_PyKDL[1243]
#define sipNameNr__maxiter 1252
#define sipName__maxiter &sipStrings_PyKDL[1252]
#define sipNameNr_iksolver 1261
#define sipName_iksolver &sipStrings_PyKDL[1261]
#define sipNameNr_fksolver 1270
#define sipName_fksolver &sipStrings_PyKDL[1270]
#define sipNameNr_qdot_out 1279
#define sipName_qdot_out &sipStrings_PyKDL[1279]
#define sipNameNr_strError 1288
#define sipName_strError &sipStrings_PyKDL[1288]
#define sipNameNr_getError 1297
#define sipName_getError &sipStrings_PyKDL[1297]
#define sipNameNr_Jacobian 446
#define sipName_Jacobian &sipStrings_PyKDL[446]
#define sipNameNr_Multiply 1306
#define sipName_Multiply &sipStrings_PyKDL[1306]
#define sipNameNr_Subtract 1315
#define sipName_Subtract &sipStrings_PyKDL[1315]
#define sipNameNr_JntArray 1324
#define sipName_JntArray &sipStrings_PyKDL[1324]
#define sipNameNr_getChain 1333
#define sipName_getChain &sipStrings_PyKDL[1333]
#define sipNameNr_addChain 1342
#define sipName_addChain &sipStrings_PyKDL[1342]
#define sipNameNr_getJoint 1351
#define sipName_getJoint &sipStrings_PyKDL[1351]
#define sipNameNr_addDelta 1360
#define sipName_addDelta &sipStrings_PyKDL[1360]
#define sipNameNr_RefPoint 526
#define sipName_RefPoint &sipStrings_PyKDL[526]
#define sipNameNr_EulerZYX 771
#define sipName_EulerZYX &sipStrings_PyKDL[771]
#define sipNameNr_EulerZYZ 783
#define sipName_EulerZYZ &sipStrings_PyKDL[783]
#define sipNameNr_Identity 1369
#define sipName_Identity &sipStrings_PyKDL[1369]
#define sipNameNr_Rotation 1378
#define sipName_Rotation &sipStrings_PyKDL[1378]
#define sipNameNr___iadd__ 1387
#define sipName___iadd__ &sipStrings_PyKDL[1387]
#define sipNameNr___isub__ 1396
#define sipName___isub__ &sipStrings_PyKDL[1396]
#define sipNameNr___repr__ 1405
#define sipName___repr__ &sipStrings_PyKDL[1405]
#define sipNameNr_gravity 1414
#define sipName_gravity &sipStrings_PyKDL[1414]
#define sipNameNr_torques 1422
#define sipName_torques &sipStrings_PyKDL[1422]
#define sipNameNr_opt_pos 1430
#define sipName_opt_pos &sipStrings_PyKDL[1430]
#define sipNameNr_weights 1438
#define sipName_weights &sipStrings_PyKDL[1438]
#define sipNameNr_maxiter 1253
#define sipName_maxiter &sipStrings_PyKDL[1253]
#define sipNameNr_SolverI 1446
#define sipName_SolverI &sipStrings_PyKDL[1446]
#define sipNameNr_base_AB 1123
#define sipName_base_AB &sipStrings_PyKDL[1123]
#define sipNameNr_newSize 1454
#define sipName_newSize &sipStrings_PyKDL[1454]
#define sipNameNr_columns 1462
#define sipName_columns &sipStrings_PyKDL[1462]
#define sipNameNr_segment 1470
#define sipName_segment &sipStrings_PyKDL[1470]
#define sipNameNr_Segment 899
#define sipName_Segment &sipStrings_PyKDL[899]
#define sipNameNr_getMass 1478
#define sipName_getMass &sipStrings_PyKDL[1478]
#define sipNameNr_getType 1486
#define sipName_getType &sipStrings_PyKDL[1486]
#define sipNameNr_getName 1494
#define sipName_getName &sipStrings_PyKDL[1494]
#define sipNameNr_damping 1502
#define sipName_damping &sipStrings_PyKDL[1502]
#define sipNameNr_inertia 1510
#define sipName_inertia &sipStrings_PyKDL[1510]
#define sipNameNr_RotAxis 1518
#define sipName_RotAxis &sipStrings_PyKDL[1518]
#define sipNameNr_Inverse 943
#define sipName_Inverse &sipStrings_PyKDL[943]
#define sipNameNr___sub__ 1526
#define sipName___sub__ &sipStrings_PyKDL[1526]
#define sipNameNr___add__ 1534
#define sipName___add__ &sipStrings_PyKDL[1534]
#define sipNameNr___div__ 1542
#define sipName___div__ &sipStrings_PyKDL[1542]
#define sipNameNr___mul__ 1550
#define sipName___mul__ &sipStrings_PyKDL[1550]
#define sipNameNr___neg__ 1558
#define sipName___neg__ &sipStrings_PyKDL[1558]
#define sipNameNr_matrix 1566
#define sipName_matrix &sipStrings_PyKDL[1566]
#define sipNameNr_rotvec 1573
#define sipName_rotvec &sipStrings_PyKDL[1573]
#define sipNameNr_seg_nr 1580
#define sipName_seg_nr &sipStrings_PyKDL[1580]
#define sipNameNr_lambda 1587
#define sipName_lambda &sipStrings_PyKDL[1587]
#define sipNameNr_q_init 1594
#define sipName_q_init &sipStrings_PyKDL[1594]
#define sipNameNr_Divide 1601
#define sipName_Divide &sipStrings_PyKDL[1601]
#define sipNameNr_factor 1608
#define sipName_factor &sipStrings_PyKDL[1608]
#define sipNameNr_resize 1615
#define sipName_resize &sipStrings_PyKDL[1615]
#define sipNameNr_getCOG 1622
#define sipName_getCOG &sipStrings_PyKDL[1622]
#define sipNameNr_origin 1629
#define sipName_origin &sipStrings_PyKDL[1629]
#define sipNameNr_offset 1636
#define sipName_offset &sipStrings_PyKDL[1636]
#define sipNameNr_TransZ 1643
#define sipName_TransZ &sipStrings_PyKDL[1643]
#define sipNameNr_TransY 1650
#define sipName_TransY &sipStrings_PyKDL[1650]
#define sipNameNr_TransX 1657
#define sipName_TransX &sipStrings_PyKDL[1657]
#define sipNameNr_W_a_p2 1664
#define sipName_W_a_p2 &sipStrings_PyKDL[1664]
#define sipNameNr_W_a_p1 1671
#define sipName_W_a_p1 &sipStrings_PyKDL[1671]
#define sipNameNr_F_a_b2 1678
#define sipName_F_a_b2 &sipStrings_PyKDL[1678]
#define sipNameNr_F_a_b1 1685
#define sipName_F_a_b1 &sipStrings_PyKDL[1685]
#define sipNameNr_R_a_b2 1692
#define sipName_R_a_b2 &sipStrings_PyKDL[1692]
#define sipNameNr_R_a_b1 1699
#define sipName_R_a_b1 &sipStrings_PyKDL[1699]
#define sipNameNr_torque 1706
#define sipName_torque &sipStrings_PyKDL[1706]
#define sipNameNr_Wrench 1713
#define sipName_Wrench &sipStrings_PyKDL[1713]
#define sipNameNr_t_this 1720
#define sipName_t_this &sipStrings_PyKDL[1720]
#define sipNameNr_GetRPY 1727
#define sipName_GetRPY &sipStrings_PyKDL[1727]
#define sipNameNr_GetRot 1734
#define sipName_GetRot &sipStrings_PyKDL[1734]
#define sipNameNr_DoRotZ 1741
#define sipName_DoRotZ &sipStrings_PyKDL[1741]
#define sipNameNr_DoRotY 1748
#define sipName_DoRotY &sipStrings_PyKDL[1748]
#define sipNameNr_DoRotX 1755
#define sipName_DoRotX &sipStrings_PyKDL[1755]
#define sipNameNr___ne__ 1762
#define sipName___ne__ &sipStrings_PyKDL[1762]
#define sipNameNr___eq__ 1769
#define sipName___eq__ &sipStrings_PyKDL[1769]
#define sipNameNr_Vector 1776
#define sipName_Vector &sipStrings_PyKDL[1776]
#define sipNameNr_string 845
#define sipName_string &sipStrings_PyKDL[845]
#define sipNameNr__grav 1783
#define sipName__grav &sipStrings_PyKDL[1783]
#define sipNameNr_f_ext 1789
#define sipName_f_ext &sipStrings_PyKDL[1789]
#define sipNameNr_q_dot 1795
#define sipName_q_dot &sipStrings_PyKDL[1795]
#define sipNameNr_q_max 1801
#define sipName_q_max &sipStrings_PyKDL[1801]
#define sipNameNr_q_min 1807
#define sipName_q_min &sipStrings_PyKDL[1807]
#define sipNameNr_q_out 1813
#define sipName_q_out &sipStrings_PyKDL[1813]
#define sipNameNr_p_out 1819
#define sipName_p_out &sipStrings_PyKDL[1819]
#define sipNameNr_frame 1825
#define sipName_frame &sipStrings_PyKDL[1825]
#define sipNameNr_deriv 1831
#define sipName_deriv &sipStrings_PyKDL[1831]
#define sipNameNr_array 1837
#define sipName_array &sipStrings_PyKDL[1837]
#define sipNameNr_chain 1843
#define sipName_chain &sipStrings_PyKDL[1843]
#define sipNameNr_Chain 1336
#define sipName_Chain &sipStrings_PyKDL[1336]
#define sipNameNr_f_tip 1849
#define sipName_f_tip &sipStrings_PyKDL[1849]
#define sipNameNr_joint 1855
#define sipName_joint &sipStrings_PyKDL[1855]
#define sipNameNr_twist 1861
#define sipName_twist &sipStrings_PyKDL[1861]
#define sipNameNr_scale 1867
#define sipName_scale &sipStrings_PyKDL[1867]
#define sipNameNr_Joint 1354
#define sipName_Joint &sipStrings_PyKDL[1354]
#define sipNameNr_force 1873
#define sipName_force &sipStrings_PyKDL[1873]
#define sipNameNr_Twist 1192
#define sipName_Twist &sipStrings_PyKDL[1192]
#define sipNameNr_theta 1879
#define sipName_theta &sipStrings_PyKDL[1879]
#define sipNameNr_alpha 1885
#define sipName_alpha &sipStrings_PyKDL[1885]
#define sipNameNr_Frame 514
#define sipName_Frame &sipStrings_PyKDL[514]
#define sipNameNr_UnitZ 1891
#define sipName_UnitZ &sipStrings_PyKDL[1891]
#define sipNameNr_UnitY 1897
#define sipName_UnitY &sipStrings_PyKDL[1897]
#define sipNameNr_UnitX 1903
#define sipName_UnitX &sipStrings_PyKDL[1903]
#define sipNameNr_gamma 1909
#define sipName_gamma &sipStrings_PyKDL[1909]
#define sipNameNr_pitch 1915
#define sipName_pitch &sipStrings_PyKDL[1915]
#define sipNameNr_Gamma 1921
#define sipName_Gamma &sipStrings_PyKDL[1921]
#define sipNameNr_angle 1927
#define sipName_angle &sipStrings_PyKDL[1927]
#define sipNameNr_Equal 1933
#define sipName_Equal &sipStrings_PyKDL[1933]
#define sipNameNr_value 1939
#define sipName_value &sipStrings_PyKDL[1939]
#define sipNameNr_PyKDL 1945
#define sipName_PyKDL &sipStrings_PyKDL[1945]
#define sipNameNr_grad 1951
#define sipName_grad &sipStrings_PyKDL[1951]
#define sipNameNr_grav 1784
#define sipName_grav &sipStrings_PyKDL[1784]
#define sipNameNr_v_in 1956
#define sipName_v_in &sipStrings_PyKDL[1956]
#define sipNameNr_p_in 1961
#define sipName_p_in &sipStrings_PyKDL[1961]
#define sipNameNr_q_in 1966
#define sipName_q_in &sipStrings_PyKDL[1966]
#define sipNameNr_dest 1971
#define sipName_dest &sipStrings_PyKDL[1971]
#define sipNameNr_src2 1976
#define sipName_src2 &sipStrings_PyKDL[1976]
#define sipNameNr_src1 1981
#define sipName_src1 &sipStrings_PyKDL[1981]
#define sipNameNr_rows 1986
#define sipName_rows &sipStrings_PyKDL[1986]
#define sipNameNr_size 1617
#define sipName_size &sipStrings_PyKDL[1617]
#define sipNameNr_Tree 1991
#define sipName_Tree &sipStrings_PyKDL[1991]
#define sipNameNr_qdot 1996
#define sipName_qdot &sipStrings_PyKDL[1996]
#define sipNameNr_pose 2001
#define sipName_pose &sipStrings_PyKDL[2001]
#define sipNameNr_type 2006
#define sipName_type &sipStrings_PyKDL[2006]
#define sipNameNr_name 1076
#define sipName_name &sipStrings_PyKDL[1076]
#define sipNameNr_None 2011
#define sipName_None &sipStrings_PyKDL[2011]
#define sipNameNr_diff 2016
#define sipName_diff &sipStrings_PyKDL[2016]
#define sipNameNr__rot 2021
#define sipName__rot &sipStrings_PyKDL[2021]
#define sipNameNr__vel 2026
#define sipName__vel &sipStrings_PyKDL[2026]
#define sipNameNr_beta 2031
#define sipName_beta &sipStrings_PyKDL[2031]
#define sipNameNr_alfa 2036
#define sipName_alfa &sipStrings_PyKDL[2036]
#define sipNameNr_axis 2041
#define sipName_axis &sipStrings_PyKDL[2041]
#define sipNameNr_roll 2046
#define sipName_roll &sipStrings_PyKDL[2046]
#define sipNameNr_Beta 2051
#define sipName_Beta &sipStrings_PyKDL[2051]
#define sipNameNr_Alfa 2056
#define sipName_Alfa &sipStrings_PyKDL[2056]
#define sipNameNr_Rot2 2061
#define sipName_Rot2 &sipStrings_PyKDL[2061]
#define sipNameNr_RotZ 1743
#define sipName_RotZ &sipStrings_PyKDL[1743]
#define sipNameNr_RotY 1750
#define sipName_RotY &sipStrings_PyKDL[1750]
#define sipNameNr_RotX 1757
#define sipName_RotX &sipStrings_PyKDL[1757]
#define sipNameNr_Norm 2066
#define sipName_Norm &sipStrings_PyKDL[2066]
#define sipNameNr_Zero 1156
#define sipName_Zero &sipStrings_PyKDL[1156]
#define sipNameNr_out 1284
#define sipName_out &sipStrings_PyKDL[1284]
#define sipNameNr_jac 2071
#define sipName_jac &sipStrings_PyKDL[2071]
#define sipNameNr_src 2075
#define sipName_src &sipStrings_PyKDL[2075]
#define sipNameNr_Add 2079
#define sipName_Add &sipStrings_PyKDL[2079]
#define sipNameNr_Iin 2083
#define sipName_Iin &sipStrings_PyKDL[2083]
#define sipNameNr_Iyz 2087
#define sipName_Iyz &sipStrings_PyKDL[2087]
#define sipNameNr_Ixz 2091
#define sipName_Ixz &sipStrings_PyKDL[2091]
#define sipNameNr_Ixy 2095
#define sipName_Ixy &sipStrings_PyKDL[2095]
#define sipNameNr_Izz 2099
#define sipName_Izz &sipStrings_PyKDL[2099]
#define sipNameNr_Iyy 2103
#define sipName_Iyy &sipStrings_PyKDL[2103]
#define sipNameNr_Ixx 2107
#define sipName_Ixx &sipStrings_PyKDL[2107]
#define sipNameNr_rot 2022
#define sipName_rot &sipStrings_PyKDL[2022]
#define sipNameNr_vel 2027
#define sipName_vel &sipStrings_PyKDL[2027]
#define sipNameNr_RPY 1730
#define sipName_RPY &sipStrings_PyKDL[1730]
#define sipNameNr_yaw 2111
#define sipName_yaw &sipStrings_PyKDL[2111]
#define sipNameNr_Rot 1737
#define sipName_Rot &sipStrings_PyKDL[1737]
#define sipNameNr_vec 1576
#define sipName_vec &sipStrings_PyKDL[1576]
#define sipNameNr_dot 1221
#define sipName_dot &sipStrings_PyKDL[1221]
#define sipNameNr_rhs 2115
#define sipName_rhs &sipStrings_PyKDL[2115]
#define sipNameNr_lhs 2119
#define sipName_lhs &sipStrings_PyKDL[2119]
#define sipNameNr_eps 2123
#define sipName_eps &sipStrings_PyKDL[2123]
#define sipNameNr_arg 2127
#define sipName_arg &sipStrings_PyKDL[2127]
#define sipNameNr__M 2131
#define sipName__M &sipStrings_PyKDL[2131]
#define sipNameNr__t 2134
#define sipName__t &sipStrings_PyKDL[2134]
#define sipNameNr__T 2137
#define sipName__T &sipStrings_PyKDL[2137]
#define sipNameNr__w 2140
#define sipName__w &sipStrings_PyKDL[2140]
#define sipNameNr__R 2143
#define sipName__R &sipStrings_PyKDL[2143]
#define sipNameNr__v 2146
#define sipName__v &sipStrings_PyKDL[2146]
#define sipNameNr__p 2149
#define sipName__p &sipStrings_PyKDL[2149]
#define sipNameNr_r2 2152
#define sipName_r2 &sipStrings_PyKDL[2152]
#define sipNameNr_r1 2155
#define sipName_r1 &sipStrings_PyKDL[2155]
#define sipNameNr_nr 1584
#define sipName_nr &sipStrings_PyKDL[1584]
#define sipNameNr_Ic 2158
#define sipName_Ic &sipStrings_PyKDL[2158]
#define sipNameNr_oc 2161
#define sipName_oc &sipStrings_PyKDL[2161]
#define sipNameNr_in 765
#define sipName_in &sipStrings_PyKDL[765]
#define sipNameNr_da 1008
#define sipName_da &sipStrings_PyKDL[1008]
#define sipNameNr_dt 2164
#define sipName_dt &sipStrings_PyKDL[2164]
#define sipNameNr_DH 2167
#define sipName_DH &sipStrings_PyKDL[2167]
#define sipNameNr_Zz 2170
#define sipName_Zz &sipStrings_PyKDL[2170]
#define sipNameNr_Yz 2173
#define sipName_Yz &sipStrings_PyKDL[2173]
#define sipNameNr_Xz 2176
#define sipName_Xz &sipStrings_PyKDL[2176]
#define sipNameNr_Zy 2179
#define sipName_Zy &sipStrings_PyKDL[2179]
#define sipNameNr_Yy 2182
#define sipName_Yy &sipStrings_PyKDL[2182]
#define sipNameNr_Xy 2185
#define sipName_Xy &sipStrings_PyKDL[2185]
#define sipNameNr_Zx 2188
#define sipName_Zx &sipStrings_PyKDL[2188]
#define sipNameNr_Yx 2191
#define sipName_Yx &sipStrings_PyKDL[2191]
#define sipNameNr_Xx 2194
#define sipName_Xx &sipStrings_PyKDL[2194]
#define sipNameNr_H 2168
#define sipName_H &sipStrings_PyKDL[2168]
#define sipNameNr_m 576
#define sipName_m &sipStrings_PyKDL[576]
#define sipNameNr_I 1452
#define sipName_I &sipStrings_PyKDL[1452]
#define sipNameNr_q 2197
#define sipName_q &sipStrings_PyKDL[2197]
#define sipNameNr_i 2199
#define sipName_i &sipStrings_PyKDL[2199]
#define sipNameNr_d 1954
#define sipName_d &sipStrings_PyKDL[1954]
#define sipNameNr_M 2132
#define sipName_M &sipStrings_PyKDL[2132]
#define sipNameNr_p 618
#define sipName_p &sipStrings_PyKDL[618]
#define sipNameNr_V 2201
#define sipName_V &sipStrings_PyKDL[2201]
#define sipNameNr_R 350
#define sipName_R &sipStrings_PyKDL[350]
#define sipNameNr_X 778
#define sipName_X &sipStrings_PyKDL[778]
#define sipNameNr_t 533
#define sipName_t &sipStrings_PyKDL[533]
#define sipNameNr_w 2113
#define sipName_w &sipStrings_PyKDL[2113]
#define sipNameNr_b 2203
#define sipName_b &sipStrings_PyKDL[2203]
#define sipNameNr_a 290
#define sipName_a &sipStrings_PyKDL[290]
#define sipNameNr_v 248
#define sipName_v &sipStrings_PyKDL[248]
#define sipNameNr_z 2089
#define sipName_z &sipStrings_PyKDL[2089]
#define sipNameNr_y 645
#define sipName_y &sipStrings_PyKDL[645]
#define sipNameNr_x 204
#define sipName_x &sipStrings_PyKDL[204]

#define sipMalloc                   sipAPI_PyKDL->api_malloc
#define sipFree                     sipAPI_PyKDL->api_free
#define sipBuildResult              sipAPI_PyKDL->api_build_result
#define sipCallMethod               sipAPI_PyKDL->api_call_method
#define sipCallProcedureMethod      sipAPI_PyKDL->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_PyKDL->api_call_error_handler
#define sipParseResultEx            sipAPI_PyKDL->api_parse_result_ex
#define sipParseResult              sipAPI_PyKDL->api_parse_result
#define sipParseArgs                sipAPI_PyKDL->api_parse_args
#define sipParseKwdArgs             sipAPI_PyKDL->api_parse_kwd_args
#define sipParsePair                sipAPI_PyKDL->api_parse_pair
#define sipInstanceDestroyed        sipAPI_PyKDL->api_instance_destroyed
#define sipConvertFromSequenceIndex sipAPI_PyKDL->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_PyKDL->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_PyKDL->api_convert_to_void_ptr
#define sipAddException             sipAPI_PyKDL->api_add_exception
#define sipNoFunction               sipAPI_PyKDL->api_no_function
#define sipNoMethod                 sipAPI_PyKDL->api_no_method
#define sipAbstractMethod           sipAPI_PyKDL->api_abstract_method
#define sipBadClass                 sipAPI_PyKDL->api_bad_class
#define sipBadCatcherResult         sipAPI_PyKDL->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_PyKDL->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_PyKDL->api_bad_operator_arg
#define sipTrace                    sipAPI_PyKDL->api_trace
#define sipTransferBack             sipAPI_PyKDL->api_transfer_back
#define sipTransferTo               sipAPI_PyKDL->api_transfer_to
#define sipTransferBreak            sipAPI_PyKDL->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_PyKDL->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_PyKDL->api_wrapper_type
#define sipWrapperType_Type         sipAPI_PyKDL->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_PyKDL->api_voidptr_type
#define sipGetPyObject              sipAPI_PyKDL->api_get_pyobject
#define sipGetAddress               sipAPI_PyKDL->api_get_address
#define sipGetMixinAddress          sipAPI_PyKDL->api_get_mixin_address
#define sipGetCppPtr                sipAPI_PyKDL->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_PyKDL->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_PyKDL->api_is_py_method
#define sipCallHook                 sipAPI_PyKDL->api_call_hook
#define sipEndThread                sipAPI_PyKDL->api_end_thread
#define sipConnectRx                sipAPI_PyKDL->api_connect_rx
#define sipDisconnectRx             sipAPI_PyKDL->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_PyKDL->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_PyKDL->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_PyKDL->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_PyKDL->api_add_type_instance
#define sipFreeSipslot              sipAPI_PyKDL->api_free_sipslot
#define sipSameSlot                 sipAPI_PyKDL->api_same_slot
#define sipPySlotExtend             sipAPI_PyKDL->api_pyslot_extend
#define sipConvertRx                sipAPI_PyKDL->api_convert_rx
#define sipAddDelayedDtor           sipAPI_PyKDL->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_PyKDL->api_can_convert_to_type
#define sipConvertToType            sipAPI_PyKDL->api_convert_to_type
#define sipForceConvertToType       sipAPI_PyKDL->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_PyKDL->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_PyKDL->api_convert_to_enum
#define sipConvertToBool            sipAPI_PyKDL->api_convert_to_bool
#define sipReleaseType              sipAPI_PyKDL->api_release_type
#define sipConvertFromType          sipAPI_PyKDL->api_convert_from_type
#define sipConvertFromNewType       sipAPI_PyKDL->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_PyKDL->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_PyKDL->api_convert_from_enum
#define sipGetState                 sipAPI_PyKDL->api_get_state
#define sipExportSymbol             sipAPI_PyKDL->api_export_symbol
#define sipImportSymbol             sipAPI_PyKDL->api_import_symbol
#define sipFindType                 sipAPI_PyKDL->api_find_type
#define sipFindNamedEnum            sipAPI_PyKDL->api_find_named_enum
#define sipBytes_AsChar             sipAPI_PyKDL->api_bytes_as_char
#define sipBytes_AsString           sipAPI_PyKDL->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_PyKDL->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_PyKDL->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_PyKDL->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_PyKDL->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_PyKDL->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_PyKDL->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_PyKDL->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_PyKDL->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_PyKDL->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_PyKDL->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_PyKDL->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_PyKDL->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_PyKDL->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_PyKDL->api_save_slot
#define sipClearAnySlotReference    sipAPI_PyKDL->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_PyKDL->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_PyKDL->api_deprecated
#define sipGetReference             sipAPI_PyKDL->api_get_reference
#define sipKeepReference            sipAPI_PyKDL->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_PyKDL->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_PyKDL->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_PyKDL->api_type_from_py_type_object
#define sipTypeScope                sipAPI_PyKDL->api_type_scope
#define sipResolveTypedef           sipAPI_PyKDL->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_PyKDL->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_PyKDL->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_PyKDL->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_PyKDL->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_PyKDL->api_enable_overflow_checking
#define sipInitMixin                sipAPI_PyKDL->api_init_mixin
#define sipExportModule             sipAPI_PyKDL->api_export_module
#define sipInitModule               sipAPI_PyKDL->api_init_module
#define sipGetInterpreter           sipAPI_PyKDL->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_PyKDL->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_PyKDL->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_PyKDL->api_get_type_user_data
#define sipPyTypeDict               sipAPI_PyKDL->api_py_type_dict
#define sipPyTypeName               sipAPI_PyKDL->api_py_type_name
#define sipGetCFunction             sipAPI_PyKDL->api_get_c_function
#define sipGetMethod                sipAPI_PyKDL->api_get_method
#define sipFromMethod               sipAPI_PyKDL->api_from_method
#define sipGetDate                  sipAPI_PyKDL->api_get_date
#define sipFromDate                 sipAPI_PyKDL->api_from_date
#define sipGetDateTime              sipAPI_PyKDL->api_get_datetime
#define sipFromDateTime             sipAPI_PyKDL->api_from_datetime
#define sipGetTime                  sipAPI_PyKDL->api_get_time
#define sipFromTime                 sipAPI_PyKDL->api_from_time
#define sipIsUserType               sipAPI_PyKDL->api_is_user_type
#define sipGetFrame                 sipAPI_PyKDL->api_get_frame
#define sipCheckPluginForType       sipAPI_PyKDL->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_PyKDL->api_unicode_new
#define sipUnicodeWrite             sipAPI_PyKDL->api_unicode_write
#define sipUnicodeData              sipAPI_PyKDL->api_unicode_data
#define sipGetBufferInfo            sipAPI_PyKDL->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_PyKDL->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_PyKDL->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_PyKDL->api_is_derived_class
#define sipGetUserObject            sipAPI_PyKDL->api_get_user_object
#define sipSetUserObject            sipAPI_PyKDL->api_set_user_object
#define sipRegisterEventHandler     sipAPI_PyKDL->api_register_event_handler
#define sipLong_AsChar              sipAPI_PyKDL->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_PyKDL->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_PyKDL->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_PyKDL->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_PyKDL->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_PyKDL->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_PyKDL->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_PyKDL->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_PyKDL->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_PyKDL->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_PyKDL->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_PyKDL->api_map_string_to_class
#define sipMapIntToClass            sipAPI_PyKDL->api_map_int_to_class
#define sipFindClass                sipAPI_PyKDL->api_find_class
#define sipFindMappedType           sipAPI_PyKDL->api_find_mapped_type
#define sipConvertToArray           sipAPI_PyKDL->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_PyKDL->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_PyKDL->api_enable_gc
#define sipPrintObject              sipAPI_PyKDL->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_PyKDL->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_PyKDL[];

#define sipType_Vector sipExportedTypes_PyKDL[36]
#define sipClass_Vector sipExportedTypes_PyKDL[36]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Vector;

#define sipType_Rotation sipExportedTypes_PyKDL[28]
#define sipClass_Rotation sipExportedTypes_PyKDL[28]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Rotation;

#define sipType_Frame sipExportedTypes_PyKDL[19]
#define sipClass_Frame sipExportedTypes_PyKDL[19]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Frame;

#define sipType_Twist sipExportedTypes_PyKDL[34]
#define sipClass_Twist sipExportedTypes_PyKDL[34]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Twist;

#define sipType_Wrench sipExportedTypes_PyKDL[38]
#define sipClass_Wrench sipExportedTypes_PyKDL[38]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Wrench;

#define sipType_Joint sipExportedTypes_PyKDL[25]
#define sipClass_Joint sipExportedTypes_PyKDL[25]->u.td_wrapper_type

#define sipType_Joint_JointType sipExportedTypes_PyKDL[26]
#define sipEnum_Joint_JointType sipExportedTypes_PyKDL[26]->u.td_py_type

extern sipClassTypeDef sipTypeDef_PyKDL_Joint;

#define sipType_RotationalInertia sipExportedTypes_PyKDL[30]
#define sipClass_RotationalInertia sipExportedTypes_PyKDL[30]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RotationalInertia;

#define sipType_RigidBodyInertia sipExportedTypes_PyKDL[27]
#define sipClass_RigidBodyInertia sipExportedTypes_PyKDL[27]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RigidBodyInertia;

#define sipType_Segment sipExportedTypes_PyKDL[31]
#define sipClass_Segment sipExportedTypes_PyKDL[31]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Segment;

#define sipType_Chain sipExportedTypes_PyKDL[0]
#define sipClass_Chain sipExportedTypes_PyKDL[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Chain;

#define sipType_Tree sipExportedTypes_PyKDL[33]
#define sipClass_Tree sipExportedTypes_PyKDL[33]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Tree;

#define sipType_JntArray sipExportedTypes_PyKDL[22]
#define sipClass_JntArray sipExportedTypes_PyKDL[22]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntArray;

#define sipType_JntArrayVel sipExportedTypes_PyKDL[23]
#define sipClass_JntArrayVel sipExportedTypes_PyKDL[23]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntArrayVel;

#define sipType_Jacobian sipExportedTypes_PyKDL[21]
#define sipClass_Jacobian sipExportedTypes_PyKDL[21]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Jacobian;

#define sipType_SolverI sipExportedTypes_PyKDL[32]
#define sipClass_SolverI sipExportedTypes_PyKDL[32]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_SolverI;

#define sipType_ChainFkSolverPos sipExportedTypes_PyKDL[2]
#define sipClass_ChainFkSolverPos sipExportedTypes_PyKDL[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverPos;

#define sipType_ChainFkSolverVel sipExportedTypes_PyKDL[4]
#define sipClass_ChainFkSolverVel sipExportedTypes_PyKDL[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverVel;

#define sipType_ChainFkSolverPos_recursive sipExportedTypes_PyKDL[3]
#define sipClass_ChainFkSolverPos_recursive sipExportedTypes_PyKDL[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverPos_recursive;

#define sipType_ChainFkSolverVel_recursive sipExportedTypes_PyKDL[5]
#define sipClass_ChainFkSolverVel_recursive sipExportedTypes_PyKDL[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverVel_recursive;

#define sipType_ChainIkSolverPos sipExportedTypes_PyKDL[8]
#define sipClass_ChainIkSolverPos sipExportedTypes_PyKDL[8]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos;

#define sipType_ChainIkSolverVel sipExportedTypes_PyKDL[12]
#define sipClass_ChainIkSolverVel sipExportedTypes_PyKDL[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel;

#define sipType_ChainIkSolverPos_NR sipExportedTypes_PyKDL[10]
#define sipClass_ChainIkSolverPos_NR sipExportedTypes_PyKDL[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_NR;

#define sipType_ChainIkSolverPos_NR_JL sipExportedTypes_PyKDL[11]
#define sipClass_ChainIkSolverPos_NR_JL sipExportedTypes_PyKDL[11]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_NR_JL;

#define sipType_ChainIkSolverVel_pinv sipExportedTypes_PyKDL[13]
#define sipClass_ChainIkSolverVel_pinv sipExportedTypes_PyKDL[13]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv;

#define sipType_ChainIkSolverVel_wdls sipExportedTypes_PyKDL[16]
#define sipClass_ChainIkSolverVel_wdls sipExportedTypes_PyKDL[16]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_wdls;

#define sipType_ChainIkSolverPos_LMA sipExportedTypes_PyKDL[9]
#define sipClass_ChainIkSolverPos_LMA sipExportedTypes_PyKDL[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_LMA;

#define sipType_ChainIkSolverVel_pinv_nso sipExportedTypes_PyKDL[15]
#define sipClass_ChainIkSolverVel_pinv_nso sipExportedTypes_PyKDL[15]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv_nso;

#define sipType_ChainIkSolverVel_pinv_givens sipExportedTypes_PyKDL[14]
#define sipClass_ChainIkSolverVel_pinv_givens sipExportedTypes_PyKDL[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv_givens;

#define sipType_ChainJntToJacSolver sipExportedTypes_PyKDL[18]
#define sipClass_ChainJntToJacSolver sipExportedTypes_PyKDL[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainJntToJacSolver;

#define sipType_ChainJntToJacDotSolver sipExportedTypes_PyKDL[17]
#define sipClass_ChainJntToJacDotSolver sipExportedTypes_PyKDL[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainJntToJacDotSolver;

#define sipType_ChainIdSolver sipExportedTypes_PyKDL[6]
#define sipClass_ChainIdSolver sipExportedTypes_PyKDL[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIdSolver;

#define sipType_ChainIdSolver_RNE sipExportedTypes_PyKDL[7]
#define sipClass_ChainIdSolver_RNE sipExportedTypes_PyKDL[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIdSolver_RNE;

#define sipType_doubleVel sipExportedTypes_PyKDL[39]
#define sipClass_doubleVel sipExportedTypes_PyKDL[39]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_doubleVel;

#define sipType_VectorVel sipExportedTypes_PyKDL[37]
#define sipClass_VectorVel sipExportedTypes_PyKDL[37]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_VectorVel;

#define sipType_RotationVel sipExportedTypes_PyKDL[29]
#define sipClass_RotationVel sipExportedTypes_PyKDL[29]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RotationVel;

#define sipType_FrameVel sipExportedTypes_PyKDL[20]
#define sipClass_FrameVel sipExportedTypes_PyKDL[20]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_FrameVel;

#define sipType_TwistVel sipExportedTypes_PyKDL[35]
#define sipClass_TwistVel sipExportedTypes_PyKDL[35]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_TwistVel;

#define sipType_JntSpaceInertiaMatrix sipExportedTypes_PyKDL[24]
#define sipClass_JntSpaceInertiaMatrix sipExportedTypes_PyKDL[24]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntSpaceInertiaMatrix;

#define sipType_ChainDynParam sipExportedTypes_PyKDL[1]
#define sipClass_ChainDynParam sipExportedTypes_PyKDL[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainDynParam;

#define sipType_std_vector_0100Wrench sipExportedTypes_PyKDL[41]

extern sipMappedTypeDef sipTypeDef_PyKDL_std_vector_0100Wrench;

#define sipType_std_string sipExportedTypes_PyKDL[40]

extern sipMappedTypeDef sipTypeDef_PyKDL_std_string;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_PyKDL;
extern sipExportedModuleDef sipModuleAPI_PyKDL;
extern sipTypeDef *sipExportedTypes_PyKDL[];

#endif
